{% set name = "flask-postgres" %}
{% set version = "0.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flask_postgres-{{ version }}.tar.gz
  sha256: 090676705371daef3efe6fd348ff5bba12bf1cb6be48633b4e2cf9f40c307cb5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - psql=flask_postgres.cli:cli

requirements:
  host:
    - flit
    - pip
    - python >=3.6
  run:
    - click >=7.0
    - flask >=1.0
    - flask-sqlalchemy >=2.4
    - python >=3.6
    - sqlalchemy >=1.2.2

test:
  imports:
    - flask_postgres
  commands:
    - pip check
    - flask psql --help
  requires:
    - pip

about:
  home: https://github.com/dwreeves/flask-postgres
  doc_url: https://dwreeves.github.io/Flask-Postgres/
  summary: Simple CLI for managing Postgres databases in Flask.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
