{% set name = "flask-postgres" %}
{% set version = "0.2.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flask_postgres-{{ version }}.tar.gz
  sha256: bbf0f2c6689913bf3f806693d1807b736813d3637e3b0b014dc3e71c7a67726a

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - psql=flask_postgres.cli:cli

requirements:
  host:
    - flit
    - pip
    - python {{ python_min }}
  run:
    - click >=7.0
    - flask >=1.0
    - flask-sqlalchemy >=2.4
    - python >={{ python_min }}
    - sqlalchemy >=1.2.2

test:
  imports:
    - flask_postgres
  commands:
    - pip check
    - flask psql --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dwreeves/flask-postgres
  doc_url: https://dwreeves.github.io/Flask-Postgres/
  summary: Simple CLI for managing Postgres databases in Flask.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
